extract_r_and_p <- function(value = NULL, all_results=NULL, medication = F) {
  if(value == "r") {
    val <- c(all_results[[1]][[1]][["correlation"]], 
             all_results[[1]][[1]][["correlation"]], 
             all_results[[1]][[1]][["correlation nosub"]],
             all_results[[3]][[1]][["correlation"]], 
             all_results[[3]][[1]][["correlation"]], 
             all_results[[3]][[1]][["correlation nosub"]],
             all_results[[2]][[1]][["correlation"]], 
             all_results[[2]][[1]][["correlation"]], 
             all_results[[1]][[1]][["correlation nosub"]],
             all_results[[1]][[2]][["correlation"]], 
             all_results[[1]][[2]][["correlation"]], 
             all_results[[1]][[2]][["correlation nosub"]],
             all_results[[3]][[2]][["correlation"]], 
             all_results[[3]][[2]][["correlation"]], 
             all_results[[3]][[2]][["correlation nosub"]],
             all_results[[2]][[2]][["correlation"]], 
             all_results[[2]][[2]][["correlation"]], 
             all_results[[2]][[2]][["correlation nosub"]],
             all_results[[1]][[3]][["correlation"]], 
             all_results[[1]][[3]][["correlation"]], 
             all_results[[1]][[3]][["correlation nosub"]],
             all_results[[3]][[3]][["correlation"]], 
             all_results[[3]][[3]][["correlation"]], 
             all_results[[3]][[3]][["correlation nosub"]],
             all_results[[2]][[3]][["correlation"]], 
             all_results[[2]][[3]][["correlation"]], 
             all_results[[2]][[3]][["correlation nosub"]])
  }
  if(value == "p") {
    val <- c(all_results[[1]][[1]][["connectome p"]],
             all_results[[1]][[1]][["param p"]],
             all_results[[1]][[1]][["spin p"]],
             all_results[[3]][[1]][["connectome p"]],
             all_results[[3]][[1]][["param p"]],
             all_results[[3]][[1]][["spin p"]],
             all_results[[2]][[1]][["connectome p"]],
             all_results[[2]][[1]][["param p"]],
             all_results[[2]][[1]][["spin p"]],
             all_results[[1]][[2]][["connectome p"]],
             all_results[[1]][[2]][["param p"]],
             all_results[[1]][[2]][["spin p"]],
             all_results[[3]][[2]][["connectome p"]],
             all_results[[3]][[2]][["param p"]],
             all_results[[3]][[2]][["spin p"]],
             all_results[[2]][[2]][["connectome p"]],
             all_results[[2]][[2]][["param p"]],
             all_results[[2]][[2]][["spin p"]],
             all_results[[1]][[3]][["connectome p"]],
             all_results[[1]][[3]][["param p"]],
             all_results[[1]][[3]][["spin p"]],
             all_results[[3]][[3]][["connectome p"]],
             all_results[[3]][[3]][["param p"]],
             all_results[[3]][[3]][["spin p"]],
             all_results[[2]][[3]][["connectome p"]],
             all_results[[2]][[3]][["param p"]],
             all_results[[2]][[3]][["spin p"]])
    
  }
  if(medication == T) {
    if(value == "r") {
      val <- c(all_results[[1]][[4]][["correlation"]], 
               all_results[[1]][[4]][["correlation"]], 
               all_results[[1]][[4]][["correlation nosub"]],
               all_results[[3]][[4]][["correlation"]], 
               all_results[[3]][[4]][["correlation"]], 
               all_results[[3]][[4]][["correlation nosub"]],
               all_results[[2]][[4]][["correlation"]], 
               all_results[[2]][[4]][["correlation"]], 
               all_results[[1]][[4]][["correlation nosub"]],
               all_results[[1]][[5]][["correlation"]], 
               all_results[[1]][[5]][["correlation"]], 
               all_results[[1]][[5]][["correlation nosub"]],
               all_results[[3]][[5]][["correlation"]], 
               all_results[[3]][[5]][["correlation"]], 
               all_results[[3]][[5]][["correlation nosub"]],
               all_results[[2]][[5]][["correlation"]], 
               all_results[[2]][[5]][["correlation"]], 
               all_results[[2]][[5]][["correlation nosub"]])
    }
    if(value == "p") {
      val <- c(all_results[[1]][[4]][["connectome p"]],
               all_results[[1]][[4]][["param p"]],
               all_results[[1]][[4]][["spin p"]],
               all_results[[3]][[4]][["connectome p"]],
               all_results[[3]][[4]][["param p"]],
               all_results[[3]][[4]][["spin p"]],
               all_results[[2]][[4]][["connectome p"]],
               all_results[[2]][[4]][["param p"]],
               all_results[[2]][[4]][["spin p"]],
               all_results[[1]][[5]][["connectome p"]],
               all_results[[1]][[5]][["param p"]],
               all_results[[1]][[5]][["spin p"]],
               all_results[[3]][[5]][["connectome p"]],
               all_results[[3]][[5]][["param p"]],
               all_results[[3]][[5]][["spin p"]],
               all_results[[2]][[5]][["connectome p"]],
               all_results[[2]][[5]][["param p"]],
               all_results[[2]][[5]][["spin p"]])
    }
  }
  return(val)
}
